zabbix_repos:
  versions:
    - version: '3.2'
      url: https://repo.zabbix.com/zabbix/3.2/rhel/7/x86_64/
    - version: '3.4'
      url: https://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/

zabbix_repo_non_supported: https://repo.zabbix.com/non-supported/rhel/7/x86_64/

zabbix_repo_keys:
  - https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591
  - https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-79EA5ED4

zabbix_packages:
  - zabbix-server-pgsql
  - zabbix-agent

packages:
  - epel-release
  - httpd 
  - zabbix-web
  - zabbix-web-pgsql


